default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: retro_spectacle_development

test:
  <<: *default
  database: retro_spectacle_test

production:
  <<: *default
  database: retro_spectacle_production
